# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: "library/postgres:12-alpine"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '3306:5432'